Publications
============

The full publications gallery related to the Synthesizer project is available below,
ordered by date with the most recent publications first.
A single ADS library of the papers can be found 
`here <https://ui.adsabs.harvard.edu/public-libraries/DWQDegluReez1RrvswJ5AA>`_.
You can also find the :doc:`technical <technical_publications>` and 
:doc:`application <application_publications>` publications from the Synthesizer project there.