"""A submodule containing base classes for dust emission generators.

This includes generic base classes for energy-balance and scaled dust emission
emissions, as well as a utility function for calculating CMB heating effects.

These base classes are not intended to be used directly, but rather to be
inherited by specific dust emission models that implement the wrapper methods
that generate the actual dust emission spectra and then scale them
appropriately.
"""

from typing import Optional, Union

from unyt import (
    K,
    unyt_quantity,
)

from synthesizer.components.component import Component
from synthesizer.emission_models.base_model import EmissionModel
from synthesizer.emission_models.generators.generator import Generator
from synthesizer.units import accepts


@accepts(temperature=K)
def get_cmb_heating_factor(
    temperature: unyt_quantity,
    emissivity: float,
    redshift: float,
) -> tuple[float, unyt_quantity]:
    """Return the factor by which the CMB boosts the infrared luminosity.

    This will also update the temperature of the dust at redshift z.

    (See implementation in da Cunha+2013)

    Args:
        temperature (unyt_array):
            The temperature of the dust.
        emissivity (float):
            The emissivity index in the FIR (no unit)
        redshift (float):
            The redshift of the galaxy
    """
    # Temperature of CMB at redshift=0
    _T_cmb_0 = 2.73 * K
    _T_cmb_redshift = _T_cmb_0 * (1 + redshift)
    _exp_factor = 4.0 + emissivity

    # Updated temperature accounting for CMB heating
    _temperature = (
        temperature**_exp_factor
        + _T_cmb_redshift**_exp_factor
        - _T_cmb_0**_exp_factor
    ) ** (1 / _exp_factor)

    # Factor by which the CMB boosts the infrared luminosity
    cmb_factor: float = (_temperature / temperature) ** (4 + emissivity)

    return cmb_factor, _temperature


class EnergyBalanceDustEmission(Generator):
    """Dust emission base class.

    This class of models by definition requires intrinsic and attenuated
    emissions as inputs. From which the energy absorbed by dust is calculated
    to scale the re-emitted spectra generated by the model.

    Attributes:
        temperature (unyt_quantity):
            The temperature of the dust.
        cmb_factor (float):
            The multiplicative factor to account for CMB heating at
            high-redshift.
        intrinsic (str):
            The name of the intrinsic spectrum defining the unattenuated
            emission for energy balance.
        attenuated (str):
            The name of the attenuated spectrum defining the attenuated
            emission for energy balance.
    """

    temperature: Optional[unyt_quantity]
    cmb_factor: float

    @accepts(temperature=K)
    def __init__(
        self,
        intrinsic: Union[str, EmissionModel] = "intrinsic",
        attenuated: Union[str, EmissionModel] = "attenuated",
    ) -> None:
        """Initialise the base class for dust emission models.

        Args:
            temperature (unyt_array, optional):
                The temperature of the dust. If not given we will extract this
                from the component or model.
            cmb_factor (float):
                The multiplicative factor to account for CMB heating at
                high-redshift.
            intrinsic (str):
                The name of the intrinsic spectrum defining the unattenuated
                emission for energy balance.
            attenuated (str):
                The name of the attenuated spectrum defining the attenuated
                emission for energy balance.
        """
        # Call the parent init
        Generator.__init__(
            self,
            required_params=("temperature",),
            required_emissions=(intrinsic, attenuated),
        )

    def _get_energy_balance_luminosity(
        self,
        emitter: Component,
        model: EmissionModel,
    ) -> unyt_quantity:
        """Calculate the energy absorbed by dust.

        Args:
            emitter (Stars/Gas/BlackHole):
                The object emitting the emission.
            model (EmissionModel):
                The emission model generating the emission.

        Returns:
            unyt_quantity:
                The bolometric luminosity absorbed by dust.
        """
        # Extract the emissions
        emissions = self._extract_spectra(
            emitter=emitter,
            per_particle=model.per_particle,
        )

        # For ease, unpack the intrinsic and attenuated emissions
        intrinsic = emissions[self.required_emissions[0]]
        attenuated = emissions[self.required_emissions[1]]

        # Calculate the bolometric luminosity absorbed by dust
        ldust = (
            intrinsic.bolometric_luminosity - attenuated.bolometric_luminosity
        )

        return ldust


class ScaledDustEmission(Generator):
    """A base class for scaled dust emission models.

    This class of models scale a generated dust emission spectrum by a the
    bolometric luminosity of another emission.

    Attributes:
        temperature (unyt_quantity):
            The temperature of the dust, only used if not defined on the
            emitter and or model.
        cmb_factor (float):
            The multiplicative factor to account for CMB heating at
            high-redshift.
        scaler (str):
            The name of the emission to scale the dust emission by.
    """

    temperature: Optional[unyt_quantity]
    cmb_factor: float

    @accepts(temperature=K)
    def __init__(
        self,
        scaler: Union[str, EmissionModel] = "scaler",
    ) -> None:
        """Initialise the base class for scaled dust emission models.

        Args:
            temperature (unyt_array, optional):
                The temperature of the dust. If not given we will extract this
                from the component or model.
            cmb_factor (float):
                The multiplicative factor to account for CMB heating at
                high-redshift.
            scaler (str/EmissionModel):
                The name of the emission to scale the dust emission by.
        """
        # Call the parent init
        Generator.__init__(
            self,
            required_params=("temperature",),
            required_emissions=(scaler,),
        )

    def _get_scaling_luminosity(
        self,
        emitter: Union[Component],
        model: EmissionModel,
    ) -> unyt_quantity:
        """Extract the bolometric luminosity to scale the dust emission by.

        Args:
            emitter (Stars/Gas/BlackHole):
                The object emitting the emission.
            model (EmissionModel):
                The emission model generating the emission.

        Returns:
            unyt_quantity:
                The bolometric luminosity to scale the dust emission by.
        """
        # Extract the emissions
        emissions = self._extract_spectra(
            emitter=emitter,
            per_particle=model.per_particle,
        )

        # For ease, unpack the scaler emission
        scaler = emissions[self.required_emissions[0]]

        # Get the bolometric luminosity to scale by
        lscale = scaler.bolometric_luminosity

        return lscale
